# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GridFiltration <- function(FUNvalues, gridDim, maxdimension, decomposition, printProgress) {
    .Call('_LOMAR_GridFiltration', PACKAGE = 'LOMAR', FUNvalues, gridDim, maxdimension, decomposition, printProgress)
}

GridDiag <- function(FUNvalues, gridDim, maxdimension, decomposition, library, location, printProgress) {
    .Call('_LOMAR_GridDiag', PACKAGE = 'LOMAR', FUNvalues, gridDim, maxdimension, decomposition, library, location, printProgress)
}

Bottleneck <- function(Diag1, Diag2) {
    .Call('_LOMAR_Bottleneck', PACKAGE = 'LOMAR', Diag1, Diag2)
}

Wasserstein <- function(Diag1, Diag2, p) {
    .Call('_LOMAR_Wasserstein', PACKAGE = 'LOMAR', Diag1, Diag2, p)
}

Kde <- function(X, Grid, h, kertype, weight, printProgress) {
    .Call('_LOMAR_Kde', PACKAGE = 'LOMAR', X, Grid, h, kertype, weight, printProgress)
}

KdeDist <- function(X, Grid, h, weight, printProgress) {
    .Call('_LOMAR_KdeDist', PACKAGE = 'LOMAR', X, Grid, h, weight, printProgress)
}

Dtm <- function(knnDistance, weightBound, r) {
    .Call('_LOMAR_Dtm', PACKAGE = 'LOMAR', knnDistance, weightBound, r)
}

DtmWeight <- function(knnDistance, weightBound, r, knnIndex, weight) {
    .Call('_LOMAR_DtmWeight', PACKAGE = 'LOMAR', knnDistance, weightBound, r, knnIndex, weight)
}

FiltrationDiag <- function(filtration, maxdimension, library, location, printProgress) {
    .Call('_LOMAR_FiltrationDiag', PACKAGE = 'LOMAR', filtration, maxdimension, library, location, printProgress)
}

FunFiltration <- function(FUNvalues, cmplx) {
    .Call('_LOMAR_FunFiltration', PACKAGE = 'LOMAR', FUNvalues, cmplx)
}

RipsFiltration <- function(X, maxdimension, maxscale, dist, library, printProgress) {
    .Call('_LOMAR_RipsFiltration', PACKAGE = 'LOMAR', X, maxdimension, maxscale, dist, library, printProgress)
}

RipsDiag <- function(X, maxdimension, maxscale, dist, libraryFiltration, libraryDiag, location, printProgress) {
    .Call('_LOMAR_RipsDiag', PACKAGE = 'LOMAR', X, maxdimension, maxscale, dist, libraryFiltration, libraryDiag, location, printProgress)
}

